spring:
  #thymeleaf 경로 설정
  thymeleaf:
    characterEncoding: utf-8
    order: '0'
    cache: 'false'
    prefix: classpath:/templates/
    check-template-location: 'true'
    suffix: .html
  #datasource oracle cloud DB 설정
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    password: Pol20222022
    username: polstory
    url: jdbc:oracle:thin:@BasicKim?TNS_ADMIN=./src/main/resources/wallet

  security:
    #oauth 구글 로그인 기본설정
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            client-id: 651327539623-mlsck9srbcl0ih1ehe2gmdaihncre65j.apps.googleusercontent.com
            scope:
            - email
            - profile
  #jpa 기본설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        validator:
          apply_to_ddl: 'true'
        format_sql: 'true'
        show_sql: 'true'
